# Generated by Django 5.0 on 2025-12-03 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Distancia en centímetros')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor_id', models.CharField(default='DIST_01', max_length=50)),
            ],
            options={
                'verbose_name': 'Distancia',
                'verbose_name_plural': 'Distancias',
                'db_table': 'distancia',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Humedad en porcentaje')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor_id', models.CharField(default='HUM_01', max_length=50)),
            ],
            options={
                'verbose_name': 'Humedad',
                'verbose_name_plural': 'Humedades',
                'db_table': 'humedad',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Temperatura en grados Celsius')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor_id', models.CharField(default='TEMP_01', max_length=50)),
            ],
            options={
                'verbose_name': 'Temperatura',
                'verbose_name_plural': 'Temperaturas',
                'db_table': 'temperatura',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
